import { build } from 'esbuild';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';
import { createHash } from 'node:crypto';

const directory = fileURLToPath(new URL('.', import.meta.url));
const pin = JSON.parse(await readFile(join(directory, 'upstream-pin.json'), 'utf8'));
for (const [name, expected] of Object.entries(pin.files)) {
  const actual = createHash('sha256').update(await readFile(join(directory, 'upstream', name))).digest('hex');
  if (actual !== expected) throw new Error(`Modified pinned upstream schema: ${name}`);
}
const output = fileURLToPath(new URL('../../Sources/PiMacApp/Resources/t3-bridge/vendor/rpc-runtime.mjs', import.meta.url));
const result = await build({
  entryPoints: [join(directory, 'runtime.mjs')], outfile: output,
  bundle: true, platform: 'node', format: 'esm', target: 'node22',
  minify: true, write: false, legalComments: 'external',
  define: { 'process.env.WS_NO_BUFFER_UTIL': '"1"', 'process.env.WS_NO_UTF_8_VALIDATE': '"1"' },
  banner: { js: '// Generated by sidecars/t3-rpc/build.mjs. See rpc-runtime.LICENSE.txt.\nimport { createRequire as __createRequire } from "node:module"; const require = __createRequire(import.meta.url);' },
});
const notices = await Promise.all(['effect', 'ws'].map(async name =>
  `${name}\n${await readFile(join(directory, 'node_modules', name, 'LICENSE'), 'utf8')}`));
const fixture = await build({
  entryPoints: [join(directory, 'upstream-validation.mjs')],
  outfile: join(directory, 'generated/upstream-validation.mjs'),
  bundle: true, platform: 'node', format: 'esm', target: 'node22',
  minify: true, write: false, legalComments: 'external',
  banner: { js: '// Generated test-only T3 schema fixture. License: ../upstream/T3-LICENSE.txt and ../../../Sources/PiMacApp/Resources/t3-bridge/vendor/rpc-runtime.LICENSE.txt.' },
});
const artifacts = [...result.outputFiles, ...fixture.outputFiles].map(file => [file.path, file.text]);
artifacts.push([output.replace('.mjs', '.LICENSE.txt'), notices.join('\n\n').trimEnd() + '\n']);
await mkdir(fileURLToPath(new URL('../../Sources/PiMacApp/Resources/t3-bridge/vendor/', import.meta.url)), { recursive: true });
for (const [path, value] of artifacts) {
  if (process.argv.includes('--check')) {
    if (await readFile(path, 'utf8') !== value) throw new Error(`Stale generated runtime: ${path}`);
  } else { await mkdir(dirname(path), { recursive: true }); await writeFile(path, value); }
}
console.log(`T3 RPC runtime ${process.argv.includes('--check') ? 'verified' : 'built'} (${result.outputFiles[0].contents.length} bytes)`);
